server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 200
    threads:
      max: 10

spring:
  datasource:
    username: root
    password: root7777
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    redisson:
      file: classpath:redisson-single.yml
#  r2dbc:
#    url: r2dbcs:mysql://localhost:3306/mydb?sslMode=DISABLED&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
#    username: root
#    password: root
